version: "3.9"

services:
  db:
    image: mariadb:11
    container_name: logapp_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: logdb
      MYSQL_USER: loguser
      MYSQL_PASSWORD: logpass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"

  web:
    build: ./web
    container_name: logapp_web
    command: >
      python -m debugpy --listen 0.0.0.0:6666 --wait-for-client manage.py runserver 0.0.0.0:9000
    environment:
      - IS_DOCKER=true
      - DJANGO_SETTINGS_MODULE=config.settings
    volumes:
      - ./web:/app
    ports:
      - "9000:8000"
      - "6666:5678"
    depends_on:
      - db

volumes:
  db_data:
